### ISSUE TITLE
Bucket access token at AWS is kept on cloudformation console outputs

### ISSUE THREAD

**Issue by devopsvanilla** [devopsvanilla/mysql-k8s-backup#2]
## Suggestions to Remove CloudFormation Outputs and Protect Credentials

To remove the CloudFormation outputs while keeping the deployed resources and protect the created access credential, follow the steps below:

1. **Remove CloudFormation Outputs:**
   - Edit the file `setup/create-awss3-cfn.yaml` and remove the `Outputs` section.
   - Example:
     ```yaml
     # filepath: /home/devopsvanilla/_prj/devopsvanilla/datashelter/setup/create-awss3-cfn.yaml
     Resources:
       # ...existing resources...
     Outputs:
       # Remove this section
       BucketAccessToken:
         Description: "Access token for the S3 bucket"
         Value: !Ref BucketAccessToken
     ```

2. **Protect Access Credentials:**
   - Use AWS Secrets Manager to store and manage the access credentials.
   - Update the resources that use these credentials to fetch them from Secrets Manager.
   - Example of how to store the credential in Secrets Manager:
     ```bash
     aws secretsmanager create-secret --name MyBucketAccessToken --secret-string "your-access-token"
     ```

3. **Update IAM Policies:**
   - Ensure that only the owner or authorized users have access to the credentials stored in Secrets Manager.
   - Example of an IAM policy:
     ```json
     {
       "Version": "2012-10-17",
       "Statement": [
         {
           "Effect": "Allow",
           "Action": "secretsmanager:GetSecretValue",
           "Resource": "arn:aws:secretsmanager:region:account-id:secret:MyBucketAccessToken",
           "Condition": {
             "StringEquals": {
               "aws:username": "owner-username"
             }
           }
         }
       ]
     }
